### ISSUE TITLE
Is there a way to get auth token?

### ISSUE THREAD

**Issue by kresent** [yy-bird/pixelknight#1]
Good day. I See you use many pss methods, that require authentication. How do you get the token?

**Comment by yy-bird** [comment]
Wow, you start playing this game? I haven't open it for a long time since they banned my main account lol.
Anyway, you can use proxy to intercept the network traffic. I was using fiddler. I believe any similar software can do the magic. Don't abuse the api. They will ban you for real.

**Comment by kresent** [comment]
Thanks, good to know. Seems like only public api is safe for usage.
